# Generated by Django 3.1.5 on 2021-03-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbid',
            name='product',
        ),
        migrations.DeleteModel(
            name='ActiveList',
        ),
        migrations.DeleteModel(
            name='UserBid',
        ),
    ]
