# Generated by Django 3.1.5 on 2021-03-20 00:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0003_activelist_userbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbid',
            name='bider',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.activelist'),
        ),
        migrations.AlterField(
            model_name='userbid',
            name='userbid',
            field=models.IntegerField(),
        ),
    ]
