# Generated by Django 3.1.5 on 2021-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
