# Generated by Django 3.1.5 on 2021-03-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_chek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chek',
        ),
    ]
